language: c
cache: ccache

sudo: false

env:
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3


before_install:
  - source .travis/setenv_lua.sh

install: true

script:
  - ./checklua.sh

notifications:
  email:
    on_success: change
    on_failure: always
